[2024-02-12 14:05:18,504] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-06T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:05:18,510] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-06T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:05:18,510] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:05:18,510] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 14:05:18,510] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:05:18,516] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_item> on 2024-02-06 14:01:59.240675+00:00
[2024-02-12 14:05:18,519] {standard_task_runner.py:52} INFO - Started process 28326 to run task
[2024-02-12 14:05:18,520] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_item', 'scheduled__2024-02-06T14:01:59.240675+00:00', '--job-id', '549', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmp7vemdy_j', '--error-file', '/tmp/tmpc2vd_u46']
[2024-02-12 14:05:18,520] {standard_task_runner.py:80} INFO - Job 549: Subtask update_d_item
[2024-02-12 14:05:18,551] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-06T14:01:59.240675+00:00 [running]> on host 91766ce79ef0
[2024-02-12 14:05:18,586] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_item
AIRFLOW_CTX_EXECUTION_DATE=2024-02-06T14:01:59.240675+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-06T14:01:59.240675+00:00
[2024-02-12 14:05:18,592] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 14:05:18,596] {sql.py:315} INFO - Running statement: insert into 
    mart.d_item (item_id, 
        item_name)
select 
    item_id, 
    item_name 
from staging.user_order_log
where item_id not in (select item_id from mart.d_item)
group by item_id, item_name, parameters: None
[2024-02-12 14:05:18,597] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 14:05:18,604] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_item, execution_date=20240206T140159, start_date=20240212T140518, end_date=20240212T140518
[2024-02-12 14:05:18,612] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 14:05:18,633] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
