[2024-02-12 10:01:20,387] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales manual__2024-02-12T09:59:49.063603+00:00 [queued]>
[2024-02-12 10:01:20,392] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_f_sales manual__2024-02-12T09:59:49.063603+00:00 [queued]>
[2024-02-12 10:01:20,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:01:20,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 10:01:20,392] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:01:20,399] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_sales> on 2024-02-12 09:59:49.063603+00:00
[2024-02-12 10:01:20,402] {standard_task_runner.py:52} INFO - Started process 18421 to run task
[2024-02-12 10:01:20,403] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_f_sales', 'manual__2024-02-12T09:59:49.063603+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart.py', '--cfg-path', '/tmp/tmpjm26jsou', '--error-file', '/tmp/tmppgivg34r']
[2024-02-12 10:01:20,404] {standard_task_runner.py:80} INFO - Job 393: Subtask update_f_sales
[2024-02-12 10:01:20,436] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_f_sales manual__2024-02-12T09:59:49.063603+00:00 [running]> on host 91766ce79ef0
[2024-02-12 10:01:20,472] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_f_sales
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T09:59:49.063603+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T09:59:49.063603+00:00
[2024-02-12 10:01:20,478] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 10:01:20,481] {sql.py:315} INFO - Running statement: insert into mart.f_sales (date_id, item_id, customer_id, city_id, quantity, payment_amount)
select 
    dc.date_id, 
    item_id, 
    customer_id, 
    city_id, 
    quantity, 
case when uol.status='refunded'  then payment_amount*-1 else payment_amount end as payment_amount
from staging.user_order_log uol
left join mart.d_calendar as dc on uol.date_time::Date = dc.date_actual
;, parameters: {'date': ('{{ ds }}',)}
[2024-02-12 10:01:20,558] {sql.py:324} INFO - Rows affected: 4675
[2024-02-12 10:01:20,570] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_f_sales, execution_date=20240212T095949, start_date=20240212T100120, end_date=20240212T100120
[2024-02-12 10:01:20,616] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 10:01:20,640] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
