[2024-02-12 07:36:59,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.upload_customer_research_inc scheduled__2024-02-09T07:30:05.907678+00:00 [queued]>
[2024-02-12 07:36:59,914] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.upload_customer_research_inc scheduled__2024-02-09T07:30:05.907678+00:00 [queued]>
[2024-02-12 07:36:59,914] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:36:59,914] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 07:36:59,914] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:36:59,920] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_customer_research_inc> on 2024-02-09 07:30:05.907678+00:00
[2024-02-12 07:36:59,923] {standard_task_runner.py:52} INFO - Started process 5484 to run task
[2024-02-12 07:36:59,925] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'upload_customer_research_inc', 'scheduled__2024-02-09T07:30:05.907678+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/sprint3 copy 2.py', '--cfg-path', '/tmp/tmpwba3_gym', '--error-file', '/tmp/tmpsugutwbn']
[2024-02-12 07:36:59,925] {standard_task_runner.py:80} INFO - Job 101: Subtask upload_customer_research_inc
[2024-02-12 07:36:59,958] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.upload_customer_research_inc scheduled__2024-02-09T07:30:05.907678+00:00 [running]> on host 91766ce79ef0
[2024-02-12 07:36:59,992] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=upload_customer_research_inc
AIRFLOW_CTX_EXECUTION_DATE=2024-02-09T07:30:05.907678+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-09T07:30:05.907678+00:00
[2024-02-12 07:36:59,992] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_data_to_staging() missing 1 required positional argument: 'b_inc'
[2024-02-12 07:36:59,999] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart_inc, task_id=upload_customer_research_inc, execution_date=20240209T073005, start_date=20240212T073659, end_date=20240212T073659
[2024-02-12 07:37:00,004] {standard_task_runner.py:92} ERROR - Failed to execute job 101 for task upload_customer_research_inc (upload_data_to_staging() missing 1 required positional argument: 'b_inc'; 5484)
[2024-02-12 07:37:00,017] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-12 07:37:00,042] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
